name: ask_the_menu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  flutter_markdown: ^0.7.1
  google_generative_ai: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Note: this section is only used in order to resolve google_generative_ai to
# the same repo as the sample.
dependency_overrides:
  google_generative_ai:
    path: ../../pkgs/google_generative_ai